### ISSUE TITLE
Flowroute has changed their API and the SMS callback JSON request is now different.

### ISSUE THREAD

**Issue by raffieyeah** [chriselsen/AWSLambda_FlowrouteSMS#1]
Hello,

I followed your tutorial on edge-cloud.net and was able to get my Flowroute+AWS Gateway API+AWS Lambda integration to run well.

One thing I noticed is that when I send a SMS to one of my phone numbers, the e-mail received is incomplete, please see below:

```
From: Undefined (from)
To: Undefined (to)
Message: Undefined (body)
ID: Undefined (id)
```

So I checked the Flowroute SMS Callback documentation and notice the HTTP POST request has changed from:

```
POST /runpost HTTP/1.1Content-Length: 72
Host: 54.68.158.17:11111
Content-Type: application/json
Accept-Encoding: gzip

{"to": "12066418000", "body": "Hello there from Flowroute!", "from": "18553569768", "id": "mdr1-ebb118b9b034338adfc662a8c02fd88"}
```

to this:

```
POST <sms_callback_url> HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json
{
   "data": {
       "attributes": {
           "amount_display": "$0.0040",
           "amount_nanodollars": "4000000",
           "body": "Final test",
           "direction": "inbound",
           "from": "12067392634",
           "is_mms": false,
           "message_callback_url": "https://somnxp1g47.execute-api.us-west-2.amazonaws.com/dev/sms_to_slack",
           "message_encoding": 0,
           "message_type": "longcode",
           "status": "delivered",
           "timestamp": "2017-11-16T23:45:29.37Z",
           "to": "12012673227"
       },
       "id": "mdr2-3a353498cb2811e7afa11ade1e71c584",
       "type": "message"
   }
}
```

I was wondering if you could help me update the javascript code to parse this new request? I believe it's all done using JSON.parse();.

Thank you,
Rafael

**Comment by raffieyeah** [comment]
After a bit of research and playing with the code a little bit, I changed the json.parse(); function from:

`var obj = JSON.parse(event.body);`
to
`var obj = JSON.parse(event.body).data.attributes;`

And was able to get it work properly (except for "id" which is not inside "data"."attributes"). I wonder if this is the right way to go about this?

**Comment by chriselsen** [comment]
Based on the above JSON you probably want to change the following section:

```
var obj = JSON.parse(event.body);
var to = (obj.data.attributes.to === undefined ? 'Undefined (to)' : obj.data.attributes.to);
var body = (obj.data.attributes.body === undefined ? 'Undefined (body)' : obj.data.attributes.body);
var from = (obj.data.attributes.from === undefined ? 'Undefined (from)' : obj.data.attributes.from);
var id = (obj.data.id === undefined ? 'Undefined (id)' : obj.data..id);
```

Give it a try.

**Comment by raffieyeah** [comment]
@chriselsen, that worked well! 

Another thing I noticed (if you don't mind me asking here), is that every now and then I receive two e-mails for the same text message, instead of just one. I believe this is because the Flowroute API will retry the URL if it doesn't receive a "200 OK" response within 30 seconds. My lambda function is taking about 6,000ms on average, which is relatively fast, so I am puzzled as to why that's happening. Any thoughts?
